# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Electron Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: ./desktop-app

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Check out Repository
        uses: actions/checkout@v1

      - name: Setup node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Build electron App
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          package_root: ./desktop-app
          release: ${{ startsWith(github.ref, 'ref/tags/v') }}
